### ISSUE TITLE
Active for admins? (instead of devMode)

### ISSUE THREAD

**Issue by lindseydiloreto** [mmikkel/CpFieldLinks-Craft#2]
This plugin is amazing! I just started using it regularly, and I've added it to my base install. :)

Would it be possible to have the gears visible **when logged in as an admin**, as opposed to being in `devMode`? It's fairly common to make field changes in production, while logged in as an admin. And of course, in a production environment, `devMode` is off.

I think that makes more sense anyway. The ability edit fields (and field layouts) is directly related to whether or not a user is an admin (and irrelevant to whether the system is in `devMode`).

**Comment by mmikkel** [comment]
Thanks a lot Lindsey – I completely agree on all counts.

**Comment by lindseydiloreto** [comment]
Sweet! Thanks man. :)
