### ISSUE TITLE
Incompatible with older versions of PHP

### ISSUE THREAD

**Issue by monachilada** [mmikkel/CpFieldLinks-Craft#4]
Usage of the `[]` convention for arrays is not supported on PHP 5.3 and lower, which is what I'm using. It makes the plugin crash when looking at the plugins settings page and means I therefore can't activate it.

Exact error message for reference is `Parse error: syntax error, unexpected '[' in /var/www/submodules/cpfieldlinks/cpfieldlinks/CpFieldLinksPlugin.php on line 112`

**Comment by mmikkel** [comment]
Fair enough, @monachilada – thanks for reporting!

I believe [release 1.2.1](https://github.com/mmikkel/CpFieldLinks-Craft/releases/tag/v.1.2.1) will solve your issue.

**Comment by monachilada** [comment]
Thanks, but you missed one instance on line 137 where you are still using `[]` instead of `array()`.

**Comment by mmikkel** [comment]
Ouch. Sorry about that, [v.1.2.2](https://github.com/mmikkel/CpFieldLinks-Craft/releases/tag/v.1.2.2) should sort it out. Thanks a lot, @monachilada :)
