### ISSUE TITLE
Upgrading to Craft 3

### ISSUE THREAD

**Issue by janhendrickx** [mmikkel/CpFieldLinks-Craft#5]
I absolutely love this plugin, is there any chance of upgrading it so it can be used in Craft 3 too?

**Comment by mmikkel** [comment]
Hi @janhendrickx – thanks for the nice words :)

It'll definitely, 100% for sure be ported at some point before Craft 3 ships – unless, of course, 3 ships w/ a similar feature in core (and Brad is nice enough to let me know up front).

**Comment by mmikkel** [comment]
I even created a repo for it, a good while back -> https://github.com/mmikkel/CpFieldInspect-Craft

**Comment by janhendrickx** [comment]
@mmikkel : you're welcome, I mean every last character of it, it makes my work much easer since I have instant access to field handles :-).

I've missed the repo, my bad :-)

Keep up the good work!
